#!/usr/bin/env sh

# Config
wired_interface="enp0s31f6"
wireless_interface="wlan0"
battery_interface="BAT0"
ac_interface="AC"
sep="  <span foreground='#333333'>|</span>  "

bg_alt="#1a1a1a"
fg_white="#ffffff"
fg_grey="#808080"
fg_urgent="#ea51b2"

while true
do

  # Media
  media_raw=$(playerctl metadata --format "{{ artist }} - {{ title }}" 2>/dev/null | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')
  player_status=$(playerctl status 2>/dev/null)

  if [ -n "$player_status" ]; then
      display_text=$(echo "$media_raw" | cut -c 1-35)
      [ "$player_status" = "Playing" ] && m_icon="󰐊" || m_icon="󰏤"
      media_str="<span foreground='$fg_white'>$m_icon </span> <span foreground='$fg_grey'>$display_text</span>$sep"
  else
      media_str=""
  fi

  # Time
  time_str="<span foreground='$fg_white'><b>$(date +"%H:%M")</b></span> <span foreground='$fg_grey'>$sep$(date +"%m-%d")</span> "

  # Network
  if [ -e /sys/class/net/${wireless_interface} ] && [ "$(cat /sys/class/net/${wireless_interface}/operstate)" = "up" ]; then
      ssid=$(nmcli -t -f active,ssid device wifi | grep "^yes" | cut -d: -f2)
      network="<span foreground='$fg_white'>  </span> <span foreground='$fg_grey'>${ssid:-Connected}</span>"
  elif [ -e /sys/class/net/${wired_interface} ] && [ "$(cat /sys/class/net/${wired_interface}/operstate)" = "up" ]; then
      network="<span foreground='$fg_white'>󰈀 </span>"
  else
      network="<span foreground='$fg_urgent'>  </span>"
  fi

  # Power
  if [ -d /sys/class/power_supply/${battery_interface} ]; then
      bat_cap=$(cat /sys/class/power_supply/${battery_interface}/capacity)
      [ "$(cat /sys/class/power_supply/${ac_interface}/online)" = "1" ] && p_icon="󱐋" || p_icon="  "
      power_str="<span foreground='$fg_white'>$p_icon</span> <span foreground='$fg_grey'>${bat_cap}%</span>"
  else
      power_str=""
  fi

  # Audio
  vol_raw=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
  vol_num=$(echo "$vol_raw" | awk '{print int($2*100)}')
  if echo "$vol_raw" | grep -q "\[MUTED\]"; then
      audio_str="<span foreground='$fg_grey'>  MUTED</span>"
  else
      audio_str="<span foreground='$fg_white'>  </span> <span foreground='$fg_grey'>${vol_num}%</span>"
  fi

  # Output with blocks
  echo "$media_str $network $sep $audio_str $sep $power_str $sep $time_str"
  sleep 1
done
